//! This module houses types which represent decoded PG WAL records
//! ready for the pageserver to interpret. They are derived from the original
//! WAL records, so that each struct corresponds closely to one WAL record of
//! a specific kind. They contain the same information as the original WAL records,
//! but the values are already serialized in a [`SerializedValueBatch`], which
//! is the format that the pageserver is expecting them in.
//!
//! The ingestion code uses these structs to help with parsing the WAL records,
//! and it splits them into a stream of modifications to the key-value pairs that
//! are ultimately stored in delta layers.  See also the split-out counterparts in
//! [`postgres_ffi::walrecord`].
//!
//! The pipeline which processes WAL records is not super obvious, so let's follow
//! the flow of an example XACT_COMMIT Postgres record:
//!
//! (Postgres XACT_COMMIT record)
//! |
//! |--> pageserver::walingest::WalIngest::decode_xact_record
//!      |
//!      |--> ([`XactRecord::Commit`])
//!           |
//!           |--> pageserver::walingest::WalIngest::ingest_xact_record
//!                |
//!                |--> (NeonWalRecord::ClogSetCommitted)
//!                     |
//!                     |--> write to KV store within the pageserver

pub mod record;
pub mod value;

use bytes::Bytes;
use pageserver_api::reltag::{RelTag, SlruKind};
use postgres_ffi::walrecord::{
    XlMultiXactCreate, XlMultiXactTruncate, XlRelmapUpdate, XlReploriginDrop, XlReploriginSet,
    XlSmgrTruncate, XlXactParsedRecord,
};
use postgres_ffi::{Oid, TransactionId};
use serde::{Deserialize, Serialize};
use utils::lsn::Lsn;

use crate::serialized_batch::SerializedValueBatch;

// Code generated by protobuf.
pub mod proto {
    // Tonic does derives as `#[derive(Clone, PartialEq, ::prost::Message)]`
    // we don't use these types for anything but broker data transmission,
    // so it's ok to ignore this one.
    #![allow(clippy::derive_partial_eq_without_eq)]
    // The generated ValueMeta has a `len` method generate for its `len` field.
    #![allow(clippy::len_without_is_empty)]
    include!(concat!(env!("OUT_DIR"), concat!("/interpreted_wal.rs")));
}

#[derive(Copy, Clone, Serialize, Deserialize)]
pub enum FlushUncommittedRecords {
    Yes,
    No,
}

/// A batch of interpreted WAL records
#[derive(Serialize, Deserialize)]
pub struct InterpretedWalRecords {
    pub records: Vec<InterpretedWalRecord>,
    // Start LSN of the next record after the batch.
    // Note that said record may not belong to the current shard.
    pub next_record_lsn: Lsn,
    // Inclusive start LSN of the PG WAL from which the interpreted
    // WAL records were extracted. Note that this is not necessarily the
    // start LSN of the first interpreted record in the batch.
    pub raw_wal_start_lsn: Option<Lsn>,
}

/// An interpreted Postgres WAL record, ready to be handled by the pageserver
#[derive(Serialize, Deserialize, Clone)]
pub struct InterpretedWalRecord {
    /// Optional metadata record - may cause writes to metadata keys
    /// in the storage engine
    pub metadata_record: Option<MetadataRecord>,
    /// A pre-serialized batch along with the required metadata for ingestion
    /// by the pageserver
    pub batch: SerializedValueBatch,
    /// Byte offset within WAL for the start of the next PG WAL record.
    /// Usually this is the end LSN of the current record, but in case of
    /// XLOG SWITCH records it will be within the next segment.
    pub next_record_lsn: Lsn,
    /// Whether to flush all uncommitted modifications to the storage engine
    /// before ingesting this record. This is currently only used for legacy PG
    /// database creations which read pages from a template database. Such WAL
    /// records require reading data blocks while ingesting, hence the need to flush.
    pub flush_uncommitted: FlushUncommittedRecords,
    /// Transaction id of the original PG WAL record
    pub xid: TransactionId,
}

impl InterpretedWalRecord {
    /// Checks if the WAL record is empty
    ///
    /// An empty interpreted WAL record has no data or metadata and does not have to be sent to the
    /// pageserver.
    pub fn is_empty(&self) -> bool {
        self.batch.is_empty()
            && self.metadata_record.is_none()
            && matches!(self.flush_uncommitted, FlushUncommittedRecords::No)
    }

    /// Checks if the WAL record is observed (i.e. contains only metadata
    /// for observed values)
    pub fn is_observed(&self) -> bool {
        self.batch.is_observed()
            && self.metadata_record.is_none()
            && matches!(self.flush_uncommitted, FlushUncommittedRecords::No)
    }
}

/// The interpreted part of the Postgres WAL record which requires metadata
/// writes to the underlying storage engine.
#[derive(Clone, Serialize, Deserialize)]
pub enum MetadataRecord {
    Heapam(HeapamRecord),
    Neonrmgr(NeonrmgrRecord),
    Smgr(SmgrRecord),
    Dbase(DbaseRecord),
    Clog(ClogRecord),
    Xact(XactRecord),
    MultiXact(MultiXactRecord),
    Relmap(RelmapRecord),
    Xlog(XlogRecord),
    LogicalMessage(LogicalMessageRecord),
    Standby(StandbyRecord),
    Replorigin(ReploriginRecord),
    // openGauss specific records
    UHeap(UHeapRecord),
    UHeap2(UHeap2Record),
    UndoLog(UndoLogRecord),
    UHeapUndo(UHeapUndoRecord),
    UndoAction(UndoActionRecord),
    UHeapBtree(UHeapBtreeRecord),
    UHeapBtree2(UHeapBtree2Record),
    Segpage(SegpageRecord),
    UHeapBtree3(UHeapBtree3Record),
    UHeapBtree4(UHeapBtree4Record),
}

#[derive(Clone, Serialize, Deserialize)]
pub enum HeapamRecord {
    ClearVmBits(ClearVmBits),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct ClearVmBits {
    pub new_heap_blkno: Option<u32>,
    pub old_heap_blkno: Option<u32>,
    pub vm_rel: RelTag,
    pub flags: u8,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum NeonrmgrRecord {
    ClearVmBits(ClearVmBits),
}

#[derive(Clone, Serialize, Deserialize)]
pub enum SmgrRecord {
    Create(SmgrCreate),
    Truncate(XlSmgrTruncate),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct SmgrCreate {
    pub rel: RelTag,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum DbaseRecord {
    Create(DbaseCreate),
    Drop(DbaseDrop),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct DbaseCreate {
    pub db_id: Oid,
    pub tablespace_id: Oid,
    pub src_db_id: Oid,
    pub src_tablespace_id: Oid,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct DbaseDrop {
    pub db_id: Oid,
    pub tablespace_ids: Vec<Oid>,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum ClogRecord {
    ZeroPage(ClogZeroPage),
    Truncate(ClogTruncate),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct ClogZeroPage {
    pub segno: u32,
    pub rpageno: u32,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct ClogTruncate {
    pub pageno: u32,
    pub oldest_xid: TransactionId,
    pub oldest_xid_db: Oid,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum XactRecord {
    Commit(XactCommon),
    Abort(XactCommon),
    CommitPrepared(XactCommon),
    AbortPrepared(XactCommon),
    Prepare(XactPrepare),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct XactCommon {
    pub parsed: XlXactParsedRecord,
    pub origin_id: u16,
    // Fields below are only used for logging
    pub xl_xid: TransactionId,
    pub lsn: Lsn,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct XactPrepare {
    pub xl_xid: TransactionId,
    pub data: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum MultiXactRecord {
    ZeroPage(MultiXactZeroPage),
    Create(XlMultiXactCreate),
    Truncate(XlMultiXactTruncate),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct MultiXactZeroPage {
    pub slru_kind: SlruKind,
    pub segno: u32,
    pub rpageno: u32,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum RelmapRecord {
    Update(RelmapUpdate),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct RelmapUpdate {
    pub update: XlRelmapUpdate,
    pub buf: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum XlogRecord {
    Raw(RawXlogRecord),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct RawXlogRecord {
    pub info: u8,
    pub lsn: Lsn,
    pub buf: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum LogicalMessageRecord {
    Put(PutLogicalMessage),
    #[cfg(feature = "testing")]
    Failpoint,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct PutLogicalMessage {
    pub path: String,
    pub buf: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum StandbyRecord {
    RunningXacts(StandbyRunningXacts),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct StandbyRunningXacts {
    pub oldest_running_xid: TransactionId,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum ReploriginRecord {
    Set(XlReploriginSet),
    Drop(XlReploriginDrop),
}

// openGauss specific record types

#[derive(Clone, Serialize, Deserialize)]
pub enum UHeapRecord {
    // UHeap operations
    Insert(UHeapInsertRecord),
    Delete(UHeapDeleteRecord),
    Update(UHeapUpdateRecord),
    FreezeTdSlot(UHeapFreezeTdSlotRecord),
    InvalidTdSlot(UHeapInvalidTdSlotRecord),
    Clean(UHeapCleanRecord),
    MultiInsert(UHeapMultiInsertRecord),
    NewPage(UHeapNewPageRecord),
    // Placeholder for other operations
    Generic(UHeapGenericRecord),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapInsertRecord {
    pub offnum: u16,
    pub flags: u8,
    pub has_tuple: bool,
    pub tuple_data: Option<Bytes>,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapDeleteRecord {
    pub oldxid: u32,
    pub offnum: u16,
    pub td_id: u8,
    pub flag: u8,
    pub has_undo_tuple: bool,
    pub undo_tuple: Option<Bytes>,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapUpdateRecord {
    pub oldxid: u32,
    pub old_offnum: u16,
    pub old_tuple_flag: u16,
    pub new_offnum: u16,
    pub old_tuple_td_id: u8,
    pub flags: u8,
    pub has_old_tuple: bool,
    pub has_new_tuple: bool,
    pub old_tuple: Option<Bytes>,
    pub new_tuple: Option<Bytes>,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapFreezeTdSlotRecord {
    pub latest_frozen_xid: u32,
    pub n_frozen: u16,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapInvalidTdSlotRecord {
    // Placeholder - need to determine structure
    pub data: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapCleanRecord {
    pub latest_removed_xid: u32,
    pub ndeleted: u16,
    pub ndead: u16,
    pub flags: u8,
    pub offsets: Vec<u16>,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapMultiInsertRecord {
    pub ntuples: i32,
    pub flags: u8,
    pub tuples: Vec<UHeapTupleData>,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapTupleData {
    pub datalen: i32,
    pub xid: u16,
    pub td_id: u8,
    pub locker_td_id: u8,
    pub flag: u16,
    pub flag2: u16,
    pub t_hoff: u8,
    pub data: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapNewPageRecord {
    // Placeholder - need to determine structure
    pub data: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapGenericRecord {
    pub info: u8,
    pub buf: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum UHeap2Record {
    // UHeap2 operations
    BaseShift(UHeap2BaseShiftRecord),
    Freeze(UHeap2FreezeRecord),
    ExtendTdSlots(UHeap2ExtendTdSlotsRecord),
    // Placeholder for other operations
    Generic(UHeap2GenericRecord),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeap2BaseShiftRecord {
    pub multi: bool,
    pub delta: i64,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeap2FreezeRecord {
    pub cutoff_xid: u32,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeap2ExtendTdSlotsRecord {
    pub n_prev_slots: u8,
    pub n_extended: u8,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeap2GenericRecord {
    pub info: u8,
    pub buf: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum UndoLogRecord {
    // Undo log operations - placeholder for now
    Generic(UndoLogGenericRecord),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UndoLogGenericRecord {
    pub info: u8,
    pub buf: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum UHeapUndoRecord {
    // UHeap undo operations
    Page(UHeapUndoPageRecord),
    ResetSlot(UHeapUndoResetSlotRecord),
    AbortSpecInsert(UHeapUndoAbortSpecInsertRecord),
    // Placeholder for other operations
    Generic(UHeapUndoGenericRecord),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapUndoPageRecord {
    pub data: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapUndoResetSlotRecord {
    pub urec_ptr: u64,
    pub zone_id: i32,
    pub td_slot_id: i32,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapUndoAbortSpecInsertRecord {
    pub offset: u16,
    pub zone_id: i32,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapUndoGenericRecord {
    pub info: u8,
    pub buf: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum UndoActionRecord {
    // Placeholder for UndoAction operations
    Generic(UndoActionGenericRecord),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UndoActionGenericRecord {
    pub info: u8,
    pub buf: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum UHeapBtreeRecord {
    // Placeholder for UHeapBtree operations
    Generic(UHeapBtreeGenericRecord),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapBtreeGenericRecord {
    pub info: u8,
    pub buf: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum UHeapBtree2Record {
    // Placeholder for UHeapBtree2 operations
    Generic(UHeapBtree2GenericRecord),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapBtree2GenericRecord {
    pub info: u8,
    pub buf: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum SegpageRecord {
    // Placeholder for Segpage operations
    Generic(SegpageGenericRecord),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct SegpageGenericRecord {
    pub info: u8,
    pub buf: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum UHeapBtree3Record {
    // Placeholder for UHeapBtree3 operations
    Generic(UHeapBtree3GenericRecord),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapBtree3GenericRecord {
    pub info: u8,
    pub buf: Bytes,
}

#[derive(Clone, Serialize, Deserialize)]
pub enum UHeapBtree4Record {
    // Placeholder for UHeapBtree4 operations
    Generic(UHeapBtree4GenericRecord),
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UHeapBtree4GenericRecord {
    pub info: u8,
    pub buf: Bytes,
}
